name: "✨ Feature Request"
description: Suggest a new feature or improvement for Vorssaint
title: "[Feature]: "
labels:
  - enhancement

body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: Is your feature request related to a problem?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: It would be great if Vorssaint could...
    validations:
      required: true

  - type: dropdown
    id: feature_area
    attributes:
      label: Feature Area
      options:
        - Other
        - System Monitor
        - Menu Bar
        - Volume Mixer
        - Window Switcher
        - Keep Awake
      
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / References
      description: Attach sketches, screenshots, or references.
